services:
  app:
    container_name: haibu_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - haibu_network
    environment:
      - NODE_ENV=development
    volumes:
      - .:/haibu_app
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/ping || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  db:
    container_name: haibu_db
    image: crate:latest
    ports:
      - "4200:4200"
      - "5433:5432"
    networks:
      - haibu_network
    volumes:
      - crate-data:/data

volumes:
  crate-data:

networks:
  haibu_network:
    driver: bridge