CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub VARCHAR,
  first_name VARCHAR,
  last_name VARCHAR,
  email VARCHAR,
  status VARCHAR
);

CREATE TABLE event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  invitation_due_time TIMESTAMP,
  location VARCHAR,
  color VARCHAR
);

CREATE TABLE tag (
  tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR
);

CREATE TABLE invitation (
  event_id BIGINT,
  user_id BIGINT,
  status VARCHAR,
  PRIMARY KEY (user_id, event_id),
  FOREIGN KEY (event_id) REFERENCES event(event_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE event_type (
  event_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR
);

CREATE TABLE location (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  address VARCHAR,
  link_to_map VARCHAR
);

CREATE TABLE location_tag (
  location_id BIGINT,
  tag_id BIGINT,
  PRIMARY KEY (location_id, tag_id),
  FOREIGN KEY (location_id) REFERENCES location(location_id),
  FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);

CREATE TABLE rating (
  location_id BIGINT,
  user_id BIGINT,
  rate FLOAT,
  comments VARCHAR,
  last_update TIMESTAMP,
  PRIMARY KEY (location_id, user_id),
  FOREIGN KEY (location_id) REFERENCES location(location_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);
