CREATE TABLE users (
  email VARCHAR PRIMARY KEY,
  sub VARCHAR,
  first_name VARCHAR,
  last_name VARCHAR,
  status VARCHAR
);

CREATE TABLE event_type (
  event_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR
);

CREATE TABLE event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  invitation_due_time TIMESTAMP,
  location VARCHAR,
  color VARCHAR
);

CREATE TABLE tag (
  tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR
);

CREATE TABLE invitation (
  event_id BIGINT,
  email VARCHAR,
  status VARCHAR,
  PRIMARY KEY (email, event_id),
  FOREIGN KEY (event_id) REFERENCES event(event_id),
  FOREIGN KEY (email) REFERENCES users(email)
);

CREATE TABLE location (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  address VARCHAR,
  link_to_map VARCHAR
);

CREATE TABLE location_tag (
  location_id BIGINT,
  tag_id BIGINT,
  PRIMARY KEY (location_id, tag_id),
  FOREIGN KEY (location_id) REFERENCES location(location_id),
  FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);

CREATE TABLE rating (
  location_id BIGINT,
  email VARCHAR,
  rate FLOAT,
  comments VARCHAR,
  last_update TIMESTAMP,
  PRIMARY KEY (location_id, email),
  FOREIGN KEY (location_id) REFERENCES location(location_id),
  FOREIGN KEY (email) REFERENCES users(email)
);
